import type { NextPage } from "next";
import Head from "next/head";
import Shell from "../components/Shell/Shell";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Shell>
				<main>
					<h1>
						<a className="dark:text-draculaComment text-draculaCyan" href="https://nextjs.org">Next.js</a>-Template with:
					</h1>

					<ul>
						<li>Tailwind</li>
            <li>Mantine</li>
					</ul>
				</main>
			</Shell>
		</>
	);
};

export default Home;
